RazorSysStat: fix build on ARM
The error was:
  error: no matching function for call to 'qMax(qreal, double)'

According to Qt docs that's because qreal is:
  Typedef for double on all platforms except for those using CPUs with
  ARM architectures. On ARM-based platforms, qreal is a typedef for
  float for performance reasons.